#!/bin/sh

echo " ____   ___   _____ ______      _____   ___   ____   __  _  ____  ____    ____  "
echo " |    \ /   \ / ___/|      |    |     | /   \ |    \ |  |/ ]|    ||    \  /    |"
echo " |  o  )     (   \_ |      |    |   __||     ||  D  )|  ' /  |  | |  _  ||   __|"
echo " |   _/|  O  |\__  ||_|  |_|    |  |_  |  O  ||    / |    \  |  | |  |  ||  |  |"
echo " |  |  |     |/  \ |  |  |      |   _] |     ||    \ |     \ |  | |  |  ||  |_ |"
echo " |  |  |     |\    |  |  |      |  |   |     ||  .  \|  .  | |  | |  |  ||     |"
echo " |__|   \___/  \___|  |__|      |__|    \___/ |__|\_||__|\_||____||__|__||___,_|"
echo "\n"

echo "Let's make sure we have a few things before we start...\n"
npm install
echo "We're all set! Happy forking.\n"
